version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    hostname: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
    - vpcstack
  
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - vpcstack
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=suasenha

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb:rw
    ports:
      - 8086:8086
    environment:
      #- DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influx
      - DOCKER_INFLUXDB_INIT_PASSWORD=influx
      - DOCKER_INFLUXDB_INIT_ORG=c2gases
      - DOCKER_INFLUXDB_INIT_BUCKET=c2gases
      #- DOCKER_INFLUXDB_INIT_RETENTION=
      #- DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=
    networks:
    - vpcstack

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:latest
    networks:
      - vpcstack
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=suasenha
    depends_on:
      - postgres

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-pgsql:latest
    networks:
      - vpcstack
    restart: always
    ports:
      - '8010:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=suasenha
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - zabbix-server

  zabbix-webservice:
    container_name: zabbix-webservice
    image: zabbix/zabbix-web-service:latest
    networks:
      - vpcstack
    restart: always
    ports:
      - '10053:10053'
    environment:
      - ZBX_ALLOWEDIP=zabbix-server
      #- ZBX_LISTENPORT=zabbix
      #- ZBX_DEBUGLEVEL=zabbix
      #- ZBX_TIMEOUT=suasenha
    depends_on:
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-5.0-latest
    container_name: zabbix_agent
    networks: 
      - vpcstack
    ports:
      - "10055:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:rw
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:rw
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:rw
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "ubuntu"
    depends_on:
      - zabbix-server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: 'root'
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,raintank-worldping-app
    volumes:
      - grafana-config:/etc/grafana:rw
      - grafana-data:/var/lib/grafana:rw
      - grafana-home:/usr/share/grafana:rw
    ports:
      - '8020:3000'
    depends_on:
      - zabbix-server
      - influxdb
    networks:
      - vpcstack

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    volumes:
      - nodered-data:/data:rw
    ports:
      - 1880:1880
    depends_on:
      - zabbix-server
      - mqtt
      - influxdb
    networks:
    - vpcstack

volumes:
 grafana-config:
 grafana-data:
 grafana-home:
 pgdata:
 nodered-data:
 influxdb-data:

networks:
  vpcstack: