version: '3.7'
services:
  mqtt:
    image: "eclipse-mosquitto"
    environment:
       eula: accept
       billing: # < Your form recognizer billing URL >
       apikey: # < Your form recognizer API key >
       FormRecognizer__ComputerVisionApiKey: # < Your form recognizer API key >
       FormRecognizer__ComputerVisionEndpointUri: # < Your form recognizer URI >
    volumes:
       - type: bind
         source: E:\publicpreview\output
         target: /mosquitto/config
       - type: bind
         source: E:\publicpreview\input
         target: /mosquitto/data
        - type: bind
         source: E:\publicpreview\input
         target: /mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
